def tutorial():
    print("       ")
    print("There are three types of attacks:")
    print("Attack 1: Dagger does 5 HP damage, 10 HP damage with a critical hit. The hit chance is 75%.")
    print("Attack 2: Bow and Arrow does 10 HP damage, 20 HP damage with a critical hit. Hit chance is 50%.")
    print("Attack 3: FireBall does 15 HP damage, 30 HP damage with a critical hit. The hit chance is 25%.")
    print("Every attack has a 1% chance of being a critical hit.")
    print("You can also choose to heal.")
    print("When healing, there are 4 different situations that can occur:")
    print("There is a 3/8 chance to heal 5 HP.")
    print("There is a 2/8 chance to heal 10 HP.")
    print("There is a 1/8 chance to heal 15 HP.")
    print("Finally, there is also a 2/8 chance that the healing fails, thus you heal 0 HP.")
    print("You and the enemy start on 50 HP, and yuo can't heal above this number.")
    print("The enemy has a 3/6 chance to choose Dagger.")
    print("The enemy has a 2/6 chance to choose Bow and Arrow.")
    print("The enemy has a 1/6 chance to choose FireBall.")
    print("The enemy can only choose to heal when at or under 25 HP, and then has a 1/3 chance to try to heal.")
    print("But, when the enemy is on 5 HP, and you are above 10 HP, the odds of the enemy tring to heal changes to 2/3.")
    print("         ")
    return tutorial